version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "9080:9080"
    entrypoint: ["gunicorn","-c","/conf/gunicorn.conf.py", "-w", "1", "-b", "0.0.0.0:9080", "--timeout", "120", "--workers", "4", "app:app"]
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8502:8502"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
      - streamlit
    networks:
      - app-network

networks:
  app-network:
    driver: bridge