FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


COPY app/*.py /app
COPY app/.streamlit /app/.streamlit

CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8502"]