version: '3.8'

services:
  geocoder-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gs
    ports:
      - "9080:9080"
    environment:
      - FLASK_ENV=development
    command: gunicorn --bind 0.0.0.0:9080 --log-level debug app:app